<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="loggers\HelloWorldLogger.txt"/>
        <AdditionalFiles Include="loggers\LoreImpsum.txt"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HamsterWheel.FluentCodeGenerators.Demo" Version="0.4.1-alpha-6556" />
    </ItemGroup>

</Project>
