<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HamsterWheel.FluentCodeGenerators.Demo.Use</RootNamespace>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="loggers\HelloWorldLogger.txt"/>
        <AdditionalFiles Include="loggers\HelloWorldLogger.txt"/>
        <None Remove="loggers\LoreImpsum.txt" />
        <AdditionalFiles Include="loggers\LoreImpsum.txt" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)\demo\HamsterWheel.FluentCodeGenerators.DemoSolution\HamsterWheel.FluentCodeGenerators.DemoSolution.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
