namespace HamsterWheel.FluentCodeGenerators.FluentApi.Contexts;

public interface IConstructorContext : IContext, IParametersDefinitionsBagContext<IConstructorContext>, IMemberWithTheBody<IConstructorContext>;