using FluentAssertions;
using HamsterWheel.FluentCodeGenerators.FluentApi.Contexts;
using HamsterWheel.FluentCodeGenerators.Generators;
using HamsterWheel.FluentCodeGenerators.Tokens;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace HamsterWheel.FluentCodeGenerators.UnitTests.Generators;

public class SourceCodeFileGeneratorBaseUnitTests
{
    [Fact]
    public void GenerateAndAdd_WhenDoNotProduceNewType_ThenSourceCodeFileNamedAfterGeneratorClass()
    {
        var directory = "AutoGeneratedCode";
        var namespaceName = "AutoGeneratedNamespace";
        var testGenerator = new TestIncrementalGenerator(directory, namespaceName);
        var driver = CSharpGeneratorDriver.Create(testGenerator);
        var compilation = CSharpCompilation.Create(nameof(TestIncrementalGenerator));

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);

        var generatedFiles = newCompilation.SyntaxTrees.Select(t => Path.GetFileName(t.FilePath)).ToArray();

        generatedFiles.Should().BeEquivalentTo($"{nameof(TestGenerator)}.g.cs");
    }

    [Fact]
    public void GenerateAndAdd_WhenDirectoryNamePassed_ThenGeneratedFileIsPlacedInThatDirectory()
    {
        var directory = "AutoGeneratedCode";
        var namespaceName = "AutoGeneratedNamespace";
        var testGenerator = new TestIncrementalGenerator(directory, namespaceName);
        var driver = CSharpGeneratorDriver.Create(testGenerator);
        var compilation = CSharpCompilation.Create(nameof(TestIncrementalGenerator));

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);

        var generatedFiles = newCompilation.SyntaxTrees.Select(t => Path.GetFileName(Path.GetDirectoryName(t.FilePath)))
            .ToArray();

        generatedFiles.Should().BeEquivalentTo(directory);
    }

    [Fact]
    public void GenerateAndAdd_WhenNamespacePassed_ThenFileHaveFileNamespaceScope()
    {
        var directory = "AutoGeneratedCode";
        var namespaceName = "AutoGeneratedNamespace";
        var testGenerator = new TestIncrementalGenerator(directory, namespaceName);
        var driver = CSharpGeneratorDriver.Create(testGenerator);
        var compilation = CSharpCompilation.Create(nameof(TestIncrementalGenerator));

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);

        var generatedFiles = newCompilation.SyntaxTrees
            .Select(t => t.ToString().Split("\n", StringSplitOptions.RemoveEmptyEntries)[1]).ToArray();

        generatedFiles.Should().BeEquivalentTo($"namespace {namespaceName};");
    }

    [Fact]
    public void GenerateAndAdd_WhenCalled_ThenHaveNullabilityEnabled()
    {
        var directory = "AutoGeneratedCode";
        var namespaceName = "AutoGeneratedNamespace";
        var testGenerator = new TestIncrementalGenerator(directory, namespaceName);
        var driver = CSharpGeneratorDriver.Create(testGenerator);
        var compilation = CSharpCompilation.Create(nameof(TestIncrementalGenerator));

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);

        var generatedFiles = newCompilation.SyntaxTrees.Select(t => t.ToString()).First();

        generatedFiles.Should().StartWith("#nullable enable");
    }

    public class TestIncrementalGenerator(string directory, string nameSpace) : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var additionalFilesProvider = context.CompilationProvider.Select((a, _) => a.Assembly);
            context.RegisterSourceOutput(additionalFilesProvider,
                (pc, _) => new TestGenerator(pc, directory, nameSpace.ToNamespace()).GenerateAndAdd());
        }
    }

    public class TestGenerator(
        SourceProductionContext sourceProductionContext,
        string directory,
        INamespace fileNamespace)
        : SourceCodeFileGeneratorBase(sourceProductionContext, directory, fileNamespace)
    {
        protected override void Configure(IFileScopedNamespaceContext context)
        {
        }
    }
}